export const UPDATE_FORM_STATE = "UPDATE_FORM_STATE";

export const GET_ALL_LAWYER_REQUEST = "GET_ALL_LAWYER_REQUEST";
export const GET_ALL_LAWYER_SUCCESS = "GET_ALL_LAWYER_SUCCESS";
export const GET_ALL_LAWYER_FAILURE = "GET_ALL_LAWYER_FAILURE";

export const ADD_LAWYER_REQUEST = "ADD_LAWYER_REQUEST";
export const ADD_LAWYER_SUCCESS = "ADD_LAWYER_SUCCESS";
export const ADD_LAWYER_FAILURE = "ADD_LAWYER_FAILURE";

export const GET_LAWYER_BY_ID_REQUEST = "GET_LAWYER_BY_ID_REQUEST";
export const GET_LAWYER_BY_ID_SUCCESS = "GET_LAWYER_BY_ID_SUCCESS";
export const GET_LAWYER_BY_ID_FAILURE = "GET_LAWYER_BY_ID_FAILURE";

export const LAWYER_DELETE_REQUEST = "LAWYER_DELETE_REQUEST";
export const LAWYER_DELETE_SUCCESS = "LAWYER_DELETE_SUCCESS";
export const LAWYER_DELETE_FAILURE = "LAWYER_DELETE_FAILURE";

export const UPDATE_LAWYER_REQUEST = "UPDATE_LAWYER_REQUEST";
export const UPDATE_LAWYER_SUCCESS = "UPDATE_LAWYER_SUCCESS";
export const UPDATE_LAWYER_FAILURE = "UPDATE_LAWYER_FAILURE";
